-- Require-time registration is deterministic. Each engine event is registered
-- once through scripts.events, while feature modules add their own handlers.
require('scripts.economy')
require('scripts.factions')
require('scripts.respawn')
require('scripts.chat')
require('scripts.starter')
require('scripts.logistic_limits')
require('scripts.linked_inventory')
require('scripts.market')
require('scripts.properties')
require('scripts.entrance_travel')
require('scripts.initial_technologies')
require('scripts.technology_decay')
require('scripts.crime')
require('scripts.social')
require('scripts.ships')
require('scripts.disasters')
require('scripts.player_cleanup')
require('scripts.permissions')
require('scripts.blueprint_limits')
require('scripts.gui')

local bootstrap = require('scripts.bootstrap')

script.on_init(function()
    bootstrap.run()
end)

script.on_configuration_changed(function()
    bootstrap.run()
end)
